import { Link } from 'react-router-dom';
import StatusBadge from '../../../components/crud/StatusBadge.jsx';

export const STATION_STATUS = {
  active: { label: 'Active', cls: 'status-green' },
  inactive: { label: 'Inactive', cls: 'status-red' }
};

const dash = (v) => (v ? v : <span style={{ color: 'var(--text-muted)' }}>—</span>);

export const stationColumns = [
  {
    key: 'name',
    label: 'Name',
    render: (r) => (
      <Link to={`/stations/${r.id}`} className="cell-strong" style={{ color: 'var(--primary)' }}>
        {r.name}
      </Link>
    ),
    exportValue: (r) => r.name
  },
  { key: 'code', label: 'Code', render: (r) => <span className="cell-strong">{r.code}</span> },
  { key: 'brand', label: 'Brand', render: (r) => dash(r.brand), exportValue: (r) => r.brand || '' },
  {
    key: 'city',
    label: 'Location',
    render: (r) => dash([r.city, r.state].filter(Boolean).join(', ')),
    exportValue: (r) => [r.city, r.state].filter(Boolean).join(', ')
  },
  { key: 'manager_name', label: 'Manager', render: (r) => dash(r.manager_name), exportValue: (r) => r.manager_name || '' },
  { key: 'status', label: 'Status', render: (r) => <StatusBadge value={r.status} map={STATION_STATUS} />, exportValue: (r) => r.status }
];

const STATUS_OPTIONS = [
  { value: 'active', label: 'Active' },
  { value: 'inactive', label: 'Inactive' }
];
const FUEL_UNIT_OPTIONS = [
  { value: 'gallons', label: 'Gallons' },
  { value: 'liters', label: 'Liters' }
];
const INVENTORY_METHOD_OPTIONS = [
  { value: 'FIFO', label: 'FIFO' },
  { value: 'AVERAGE', label: 'Average' }
];

// Full create/edit form. Only `name` is required; `code` is generated by the
// backend, so it isn't an input. The rest are optional and fall back to backend
// defaults. Field names match the API payload exactly.
export const stationFields = [
  { name: 'name', label: 'Station name', required: true, span: 2, validate: (v) => (v && (v.length < 2 || v.length > 255) ? 'Name must be 2–255 characters' : null) },
  { name: 'brand', label: 'Brand', placeholder: 'e.g. Shell' },
  { name: 'status', label: 'Status', type: 'select', options: STATUS_OPTIONS, defaultValue: 'active' },
  { name: 'manager_name', label: 'Manager', placeholder: 'e.g. John Doe' },

  { name: 'address', label: 'Address', span: 2 },
  { name: 'city', label: 'City' },
  { name: 'state', label: 'State' },
  { name: 'zip_code', label: 'ZIP code' },
  { name: 'country', label: 'Country' },

  { name: 'phone', label: 'Phone' },
  { name: 'email', label: 'Email', type: 'email', validate: (v) => (v && !/^[^@]+@[^@]+\.[^@]+$/.test(v) ? 'Invalid email' : null) },
  { name: 'latitude', label: 'Latitude', type: 'number', step: 'any', validate: (v) => (v !== '' && (v < -90 || v > 90) ? 'Must be between -90 and 90' : null) },
  { name: 'longitude', label: 'Longitude', type: 'number', step: 'any', validate: (v) => (v !== '' && (v < -180 || v > 180) ? 'Must be between -180 and 180' : null) },
  { name: 'timezone', label: 'Timezone', placeholder: 'e.g. America/Chicago' },

  { name: 'fuel_unit', label: 'Fuel unit', type: 'select', options: FUEL_UNIT_OPTIONS, defaultValue: 'gallons' },
  { name: 'inventory_method', label: 'Inventory method', type: 'select', options: INVENTORY_METHOD_OPTIONS, defaultValue: 'FIFO' },
  { name: 'default_tax_rate', label: 'Default tax rate (%)', type: 'number', step: '0.01', min: 0 },
  { name: 'low_fuel_threshold_percent', label: 'Low fuel threshold (%)', type: 'number', min: 0, validate: (v) => (v !== '' && (v < 0 || v > 100) ? 'Must be between 0 and 100' : null) },
  { name: 'last_inspection_date', label: 'Last inspection date', type: 'date' },

  { name: 'is_24_hours', label: 'Open 24 hours', type: 'checkbox' },
  { name: 'shift_based_operation', label: 'Shift-based operation', type: 'checkbox' },
  { name: 'auto_close_shift', label: 'Auto-close shift', type: 'checkbox' },
  { name: 'epa_enabled', label: 'EPA enabled', type: 'checkbox' }
];

export { STATUS_OPTIONS };
